ALTER TABLE users ADD COLUMN allow_ftp INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN allow_ftps INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN allow_scp INTEGER NOT NULL DEFAULT 0;
