package configcmd

import (
	"fmt"
	"os"
)

func Run(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("usage: filecrusher config <generate>")
	}
	switch args[0] {
	case "generate":
		return runGenerate()
	default:
		return fmt.Errorf("unknown config command: %s", args[0])
	}
}

func runGenerate() error {
	_, err := os.Stdout.WriteString(configTemplate)
	return err
}

const configTemplate = `# FileCrusher configuration file.
# Generate a fresh copy: filecrusher config generate > filecrusher.yaml

# ── Logging ──────────────────────────────────────────────────────────────────
log:
  # Log verbosity: debug, info, warning, error.
  level: "info"

# ── Database ─────────────────────────────────────────────────────────────────
db:
  # Path to the SQLite database file.
  # Created automatically on first run by "filecrusher setup".
  path: "./data/filecrusher.db"

# Directory for generated keys, certificates, and other data files.
data_dir: "./data"

# ── HTTPS / Web UI ──────────────────────────────────────────────────────────
http:
  # IP address to bind the HTTPS server to.
  # Use "0.0.0.0" to listen on all interfaces.
  bind: "127.0.0.1"

  # HTTPS port for the Web UI, admin API, and WebDAV.
  port: 5132

  # Maximum upload size per request, in megabytes (1–102400).
  max_upload_mb: 512

  # Web UI theme: "simple" (classic) or "modern" (contemporary dark).
  theme: "simple"

  tls:
    # Paths to TLS certificate and private key in PEM format.
    # Leave empty to use the self-signed pair generated by "filecrusher setup".
    cert_path: ""
    key_path: ""

# ── SSH / SFTP ───────────────────────────────────────────────────────────────
ssh:
  # Bind address for the SSH server. Defaults to the http.bind value.
  bind: ""

  # SSH port for SFTP file transfers.
  port: 2022

  # Path to the SSH host key. Leave empty to use the key generated by setup.
  host_key_path: ""

# ── FTP (plaintext) ─────────────────────────────────────────────────────────
ftp:
  # Enable the plaintext FTP server. Insecure — prefer FTPS.
  enable: false

  # Allow clients to upgrade to TLS via AUTH TLS on this port.
  explicit_tls: false

  # Disable active-mode data connections (PORT/EPRT) when true.
  disable_active_mode: false

  # FTP control port.
  port: 2121

  # Port range for passive-mode data connections (format: "start-end").
  passive_ports: "50000-50100"

  # Public IP/hostname advertised in PASV responses.
  # Required when running behind NAT or in a container.
  public_host: ""

# ── FTPS (explicit TLS) ─────────────────────────────────────────────────────
ftps:
  # Enable the explicit-TLS FTP server.
  # Requires http.tls.cert_path and http.tls.key_path to be set.
  enable: false

  # FTPS control port.
  port: 2122

  # Passive port range. Defaults to ftp.passive_ports if empty.
  passive_ports: ""

  # Public IP/hostname for PASV responses. Defaults to ftp.public_host if empty.
  public_host: ""

# ── FTPS implicit ────────────────────────────────────────────────────────────
ftps_implicit:
  # Enable the implicit-TLS FTP server (TLS from connection start, no STARTTLS).
  # Requires http.tls.cert_path and http.tls.key_path to be set.
  enable: false

  # Implicit FTPS control port (traditionally 990).
  port: 990

  # Passive port range. Defaults to ftp.passive_ports if empty.
  passive_ports: ""

  # Public IP/hostname for PASV responses. Defaults to ftp.public_host if empty.
  public_host: ""

# ── WebDAV ───────────────────────────────────────────────────────────────────
webdav:
  # Enable WebDAV access over HTTPS.
  enable: false

  # URL path prefix for WebDAV endpoints.
  prefix: "/webdav"
`
